[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    # ✅ السياسة النهائية (كسطر واحد صحيح)
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://flagcdn.com data: https://www.w3schools.com; media-src 'self' https://www.w3schools.com; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com https://cdn.tailwindcss.com; style-src 'self' https://fonts.googleapis.com https://unpkg.com 'sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY=' 'sha256-rcCjuaUgw3Cx482/twGM0HGI1rOwAWs8R+P9y3C7pJc=' 'sha256-Id0I4XaldliPfC0StQjpPfa5KJvy6Uty9mAeVYyDrWM=' 'sha256-SS+njLJu4SzR24Whei68YLi38QoCgpIUTfIfmQ9ouEw=' 'sha256-c7U7WXz6t9uJycYVTyFNe0BmbTIN8xPFolo2kqok9zU=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-MxL9r0LyLF5RB+6c/iub6JPJzHjDrHlGlFG9xWKH05I=' 'sha256-Czi+Fb+5//VgSqnmAmqe294NfoulzaRqXXN4N05xaug=' 'sha256-fXZTMerZd1cZBiFflLaQk4P7MGh3oAX7UUhlRoSVtQ8='; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://cdn.jsdelivr.net https://unpkg.com https://api.web3forms.com https://ingesteer.services-prod.nsvcs.net; form-action 'self' https://api.web3forms.com; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests;"
      
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
