[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://flagcdn.com data:; media-src 'self' https://www.w3schools.com; script-src 'self' 'sha256-U12S1lNInMTrpM1iXgXJtpGWs/sX2HiPDfl6Hi9S/ZM=' 'unsafe-hashes' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com https://cdn.tailwindcss.com; style-src 'self' https://fonts.googleapis.com https://unpkg.com 'unsafe-hashes'; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://cdn.jsdelivr.net https://unpkg.com https://api.web3forms.com https://ingesteer.services-prod.nsvcs.net; form-action 'self' https://api.web3forms.com; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; upgrade-insecure-requests;"
    
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # ğŸ”’ ÙŠÙ…ÙƒÙ†Ùƒ ØªÙØ¹ÙŠÙ„ HSTS Ù„Ø§Ø­Ù‚Ù‹Ø§ Ø¨Ø¹Ø¯ Ø§Ù„ØªØ£ÙƒØ¯ Ù…Ù† Ø£Ù† HTTPS ÙŠØ¹Ù…Ù„ Ø¯ÙˆÙ† Ù…Ø´Ø§ÙƒÙ„
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
